setupHeader();let user=null,editingId=null;const denied=document.querySelector('#adminDenied'),content=document.querySelector('#adminContent');
function getFormData(){const title=document.querySelector('#recipeTitle').value.trim(),description=document.querySelector('#recipeDescription').value.trim(),specs=document.querySelector('#recipeIngredients').value.trim(),pack=document.querySelector('#recipeSteps').value.trim();const tokens=[...new Set((title+' '+description+' '+specs).toLowerCase().replace(/[^a-zа-яё0-9 ]/gi,' ').split(/\s+/).filter(x=>x.length>1))];return{title,description,specs,package:pack,brand:document.querySelector('#recipeCategory').value,image:document.querySelector('#recipeImage').value.trim(),price:Number(document.querySelector('#recipeTime').value),memory:document.querySelector('#recipeDifficulty').value,searchTokens:tokens}}
function resetForm(){editingId=null;document.querySelector('#recipeForm').reset();document.querySelector('#recipeId').value='';document.querySelector('#formTitle').textContent='Добавить телефон';document.querySelector('#cancelEdit').classList.add('hidden')}
function fillForm(id,p){editingId=id;document.querySelector('#recipeId').value=id;document.querySelector('#recipeTitle').value=p.title||'';document.querySelector('#recipeDescription').value=p.description||'';document.querySelector('#recipeCategory').value=p.brand||'Apple';document.querySelector('#recipeImage').value=p.image||'';document.querySelector('#recipeTime').value=p.price||0;document.querySelector('#recipeDifficulty').value=p.memory||'128 ГБ';document.querySelector('#recipeIngredients').value=p.specs||'';document.querySelector('#recipeSteps').value=p.package||'';document.querySelector('#formTitle').textContent='Редактировать телефон';document.querySelector('#cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#cancelEdit').addEventListener('click',resetForm);
document.querySelector('#recipeForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.querySelector('#adminMsg');msg.textContent='Сохранение…';try{const data=getFormData();if(editingId)await db.collection('products').doc(editingId).update({...data,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});else await db.collection('products').add({...data,rating:0,reviewCount:0,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:user.uid});msg.textContent='Готово.';if(!editingId)resetForm()}catch(e){msg.textContent=e.message}});
function renderProducts(snap){document.querySelector('#recipeTotal').textContent=snap.size;document.querySelector('#adminRecipes').innerHTML=snap.docs.map(d=>{const p=d.data();return `<div class="admin-row"><img src="${imageFallback(escapeHtml(p.image))}" alt=""><div><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.brand)} • ${Number(p.price||0).toLocaleString('ru-RU')} ₸ • ★ ${(p.rating||0).toFixed(1)}</small></div><div class="admin-actions"><button class="btn btn-outline edit" data-id="${d.id}">Изменить</button><button class="btn btn-danger delete" data-id="${d.id}">Удалить</button></div></div>`}).join('');document.querySelectorAll('.edit').forEach(b=>b.addEventListener('click',async()=>{const s=await db.collection('products').doc(b.dataset.id).get();if(s.exists)fillForm(s.id,s.data())}));document.querySelectorAll('.delete').forEach(b=>b.addEventListener('click',async()=>{if(confirm('Удалить телефон?'))await db.collection('products').doc(b.dataset.id).delete()}))}
function renderUsers(snap){document.querySelector('#userTotal').textContent=snap.size;document.querySelector('#usersList').innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="admin-row" style="grid-template-columns:1fr auto"><div><strong>${escapeHtml(x.name||'Без имени')}</strong><small>${escapeHtml(x.email||d.id)}</small></div><select class="role-select" data-id="${d.id}"><option value="user" ${x.role==='user'?'selected':''}>user</option><option value="admin" ${x.role==='admin'?'selected':''}>admin</option></select></div>`}).join('');document.querySelectorAll('.role-select').forEach(s=>s.addEventListener('change',async()=>db.collection('users').doc(s.dataset.id).update({role:s.value})))}
auth.onAuthStateChanged(async current=>{user=current;if(!user){location.href='auth.html';return}const profile=await db.collection('users').doc(user.uid).get();if(!profile.exists||profile.data().role!=='admin'){denied.classList.remove('hidden');return}content.classList.remove('hidden');db.collection('products').orderBy('createdAt','desc').onSnapshot(renderProducts);db.collection('users').onSnapshot(renderUsers);const products=await db.collection('products').get();document.querySelector('#reviewTotal').textContent=products.docs.reduce((n,d)=>n+(d.data().reviewCount||0),0)});
