setupHeader();
const grid=document.querySelector('#recipesGrid'), empty=document.querySelector('#emptyState'), loadMore=document.querySelector('#loadMoreBtn');
const searchInput=document.querySelector('#searchInput'), categoryFilter=document.querySelector('#categoryFilter'), sortSelect=document.querySelector('#sortSelect'), status=document.querySelector('#catalogStatus');
let lastDoc=null, debounceTimer;
function card(docSnap){const p=docSnap.data();return `<article class="recipe-card"><a href="detail.html?id=${docSnap.id}"><img class="recipe-img" src="${imageFallback(escapeHtml(p.image))}" alt="${escapeHtml(p.title)}" loading="lazy"><div class="recipe-body"><span class="tag">${escapeHtml(p.brand || p.category || "Смартфон")}</span><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.description)}</p><div class="meta"><span>💰 ${formatPrice(p.price)} ₸</span><span>★ ${(p.rating||0).toFixed(1)}</span></div></div></a><div class="card-cart"><button class="btn btn-primary full add-cart" data-id="${docSnap.id}">🛒 В корзину</button></div></article>`}
function formatPrice(v){return Number(v||0).toLocaleString('ru-RU')}
async function loadPhones(reset=false){const term=searchInput.value.trim().toLowerCase();const brand=categoryFilter.value;const sort=sortSelect.value;if(reset){lastDoc=null;grid.innerHTML=''}status.textContent='Загрузка…';try{let ref=db.collection('products');if(term)ref=ref.where('searchTokens','array-contains',term.split(/\s+/)[0]);if(brand)ref=ref.where('brand','==',brand);let field=sort==='rating'?'rating':sort==='price'?'price':'createdAt';ref=ref.orderBy(field,sort==='price'?'asc':'desc').limit(8);if(lastDoc)ref=ref.startAfter(lastDoc);const snap=await ref.get();if(snap.docs.length)lastDoc=snap.docs[snap.docs.length-1];const html=snap.docs.map(card).join('');if(reset)grid.innerHTML=html;else grid.insertAdjacentHTML('beforeend',html);bindCartButtons();empty.classList.toggle('hidden',grid.children.length!==0);loadMore.classList.toggle('hidden',snap.size<8);status.textContent=`Показано: ${grid.children.length}`}catch(e){console.error(e);status.textContent=e.code==='failed-precondition'?'Нужен индекс Firestore — открой ссылку из Console.':'Ошибка запроса';if(reset)grid.innerHTML=`<div class="empty"><div>⚠️</div><h3>Не удалось загрузить каталог</h3><p>${escapeHtml(e.message)}</p></div>`}}
loadMore.addEventListener('click',()=>loadPhones(false));categoryFilter.addEventListener('change',()=>loadPhones(true));sortSelect.addEventListener('change',()=>loadPhones(true));searchInput.addEventListener('input',()=>{clearTimeout(debounceTimer);debounceTimer=setTimeout(()=>loadPhones(true),350)});
auth.onAuthStateChanged(()=>loadPhones(true));
db.collection('products').orderBy('createdAt','desc').limit(6).onSnapshot(snap=>{document.querySelector('#liveRecipes').innerHTML=snap.docs.map(d=>{const p=d.data();return `<a class="mini-card" href="detail.html?id=${d.id}"><img src="${imageFallback(escapeHtml(p.image))}" alt=""><div><b>${escapeHtml(p.title)}</b><span>${escapeHtml(p.brand)} • ${formatPrice(p.price)} ₸</span></div></a>`}).join('')},e=>console.error('Real-time:',e));
loadPhones(true);

function bindCartButtons(){ document.querySelectorAll('.add-cart').forEach(btn=>{ if(btn.dataset.bound)return; btn.dataset.bound='1'; btn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation(); const snap=await db.collection('products').doc(btn.dataset.id).get(); if(!snap.exists)return; const p=snap.data(); addToCart({id:snap.id,...p}); btn.textContent='✓ Добавлено'; setTimeout(()=>btn.textContent='🛒 В корзину',1000); }); }); }
