setupHeader();const detail=document.querySelector('#detail'),id=new URLSearchParams(location.search).get('id');let currentUser=null,saved=false;
function list(text=''){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}
function money(v){return Number(v||0).toLocaleString('ru-RU')+' ₸'}
async function render(){if(!id){detail.innerHTML="<div class='empty'><h2>Телефон не найден</h2></div>";return}const snap=await db.collection('products').doc(id).get();if(!snap.exists){detail.innerHTML="<div class='empty'><h2>Телефон не найден</h2></div>";return}const p=snap.data();if(currentUser)saved=(await db.collection('users').doc(currentUser.uid).collection('saved').doc(id).get()).exists;detail.innerHTML=`<article class="detail-card"><img class="detail-image" src="${imageFallback(escapeHtml(p.image))}" alt="${escapeHtml(p.title)}"><div class="detail-content"><span class="tag">${escapeHtml(p.brand)}</span><h1>${escapeHtml(p.title)}</h1><p>${escapeHtml(p.description)}</p><div class="detail-meta"><span class="tag">${money(p.price)}</span><span class="tag">${escapeHtml(p.memory||'')}</span><span class="tag">★ ${(p.rating||0).toFixed(1)}</span></div><div class="action-row"><button id="buyBtn" class="btn btn-primary">🛒 В корзину</button><button id="saveBtn" class="btn btn-outline">${saved?'✓ В избранном':'♡ В избранное'}</button><div class="rating"><button class="star" data-rating="1">★1</button><button class="star" data-rating="2">★2</button><button class="star" data-rating="3">★3</button><button class="star" data-rating="4">★4</button><button class="star" data-rating="5">★5</button></div></div><p id="detailMsg" class="form-message"></p><div class="detail-columns"><div><h3>Характеристики</h3><ul>${list(p.specs)}</ul></div><div><h3>Комплектация</h3><ul>${list(p.package)}</ul></div></div></div></article>`;document.querySelector('#saveBtn').addEventListener('click',toggleSave);document.querySelector('#buyBtn').addEventListener('click',buy);document.querySelectorAll('.star').forEach(b=>b.addEventListener('click',()=>rate(Number(b.dataset.rating))))}
async function requireUser(){if(!currentUser){location.href='auth.html';return false}return true}
async function toggleSave(){if(!(await requireUser()))return;const ref=db.collection('users').doc(currentUser.uid).collection('saved').doc(id),msg=document.querySelector('#detailMsg');try{if(saved){await ref.delete();await db.collection('history').add({userId:currentUser.uid,productId:id,action:'Удалил телефон из избранного',createdAt:firebase.firestore.FieldValue.serverTimestamp()});saved=false}else{await ref.set({productId:id,savedAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('history').add({userId:currentUser.uid,productId:id,action:'Добавил телефон в избранное',createdAt:firebase.firestore.FieldValue.serverTimestamp()});saved=true}msg.textContent=saved?'Телефон добавлен в избранное.':'Телефон удалён из избранного.';document.querySelector('#saveBtn').textContent=saved?'✓ В избранном':'♡ В избранное'}catch(e){msg.textContent=e.message}}
async function buy(){
  const snap=await db.collection('products').doc(id).get();
  const msg=document.querySelector('#detailMsg');
  if(!snap.exists)return;
  const x=snap.data();
  addToCart({id:snap.id,...x});
  msg.textContent='Телефон добавлен в корзину.';
  document.querySelector('#buyBtn').textContent='✓ В корзине';
  setTimeout(()=>document.querySelector('#buyBtn').textContent='🛒 В корзину',1200);
}

async function rate(value){if(!(await requireUser()))return;try{const ref=db.collection('products').doc(id).collection('reviews').doc(currentUser.uid);await ref.set({userId:currentUser.uid,rating:value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});const reviews=await db.collection('products').doc(id).collection('reviews').get();const ratings=reviews.docs.map(x=>x.data().rating).filter(Boolean),avg=ratings.reduce((a,b)=>a+b,0)/(ratings.length||1);await db.collection('products').doc(id).update({rating:avg,reviewCount:ratings.length});await db.collection('history').add({userId:currentUser.uid,productId:id,action:`Поставил оценку ${value}/5`,createdAt:firebase.firestore.FieldValue.serverTimestamp()});document.querySelector('#detailMsg').textContent=`Оценка сохранена. Средняя: ${avg.toFixed(1)}/5`}catch(e){document.querySelector('#detailMsg').textContent=e.message}}
auth.onAuthStateChanged(user=>{currentUser=user;render().catch(e=>detail.innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`)});
